const SET_USER_INFO = "SET_USER_INFO";
const SET_DATE = "SET_DATE";
const SEARCH_USER = 'SEARCH_USER';
const DEFAULT_CATEGORY = 'DEFAULT_CATEGORY';
const SET_EDIT_DATA = 'SET_EDIT_DATA';
const SET_SUBMIT = 'SET_SUBMIT';
const SET_MY_PROJECT = 'SET_MY_PROJECT';
const SET_TASK_DETAIL = 'SET_TASK_DETAIL';
export { SET_USER_INFO, SET_DATE, SEARCH_USER, DEFAULT_CATEGORY, SET_EDIT_DATA, SET_SUBMIT, SET_MY_PROJECT, SET_TASK_DETAIL};